sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.9.12
    port: 3306
    database: company_management_system
    username: admin
    password: admin123
#    username: root
#    password: ADMIN123456
